"""Add user_role column

Revision ID: d9bb3577d78e
Revises: e2aae67e1160
Create Date: 2025-05-12 20:00:05.517034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bb3577d78e'
down_revision: Union[str, None] = 'e2aae67e1160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('is_admin', 'is_supplier', 'is_customer', name='user_role').create(op.get_bind())
    op.add_column('users', sa.Column('user_role', sa.Enum('is_admin', 'is_supplier', 'is_customer', name='user_role'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_role')
    sa.Enum('is_admin', 'is_supplier', 'is_customer', name='user_role').drop(op.get_bind())
    # ### end Alembic commands ###
