services:
  web:
    # Берем Dockerfile из каталога app
    build:
      context: .
      dockerfile: ./app/Dockerfile
    # Запускаем тестовый сервер
    command: uvicorn app.main:app --host 0.0.0.0
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env

volumes:
  postgres_data: