name: fastapi_ecommerce_prod
services:
  web:
    # Берем Dockerfile из каталога app
    build:
      context: .
      dockerfile: ./app/Dockerfile.prod
    # Запускаем сервер
    command: uvicorn app.main:app --workers 4 --host 0.0.0.0
    # Открываем порт внутри и снаружи
    # ports:
    #   - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:15
    container_name: fastapi-ecommerce-prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
  
  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data: