name: fastapi_ecommerce_prod
services:
  web:
    # Берем Dockerfile из каталога app
    build:
      context: .
      dockerfile: ./app/Dockerfile.prod
    # Запускаем сервер
    command: uvicorn app.main:app --workers 4 --host 0.0.0.0
    # Открываем порт внутри и снаружи
    # ports:
    #   - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:15
    container_name: fastapi-ecommerce-prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
  
  nginx:
    build: nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email kornilov.da.98@gmail.com --agree-tos --no-eff-email -d ntms.space
    depends_on:
      - nginx

volumes:
  postgres_data:
